# Generated by Django 2.0.9 on 2019-04-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biyografi'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ('Belirtilmemiş', 'Belirtilmemiş')], max_length=100, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Onaylandı'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon No'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/profile/', verbose_name='Profil Fotoğrafı'),
        ),
    ]
