# Generated by Django 2.0.9 on 2019-04-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0002_auto_20190406_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Onaylandı'),
        ),
    ]
