# Generated by Django 2.0.9 on 2019-04-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0003_auto_20190406_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_status',
        ),
    ]
