# Generated by Django 2.0.9 on 2019-04-05 22:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0004_remove_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='İsim')),
                ('number', models.IntegerField(unique=True, verbose_name='İl Kodu')),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehirler',
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identity_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='TC No')),
                ('executive_namesurname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Yetkili Adı Soyadı')),
                ('executive_identity_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Yetkili TC No')),
                ('executive_email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Yetkili Email')),
                ('executive_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Yetkili Telefon Numarası')),
                ('mersis_no', models.CharField(blank=True, max_length=250, null=True, verbose_name='Mersis Numarası')),
                ('kep_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Kep Adresi')),
                ('tax_office', models.CharField(blank=True, max_length=250, null=True, verbose_name='Vergi Dairesi')),
                ('tax_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Vergi No')),
                ('legal_company_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Yasal Şirket Ünvanı')),
                ('iban', models.CharField(blank=True, max_length=250, null=True, verbose_name='IBAN')),
                ('link_facebook', models.CharField(blank=True, max_length=250, null=True, verbose_name='Facebook Linki')),
                ('link_instagram', models.CharField(blank=True, max_length=250, null=True, verbose_name='Instagram Linki')),
                ('link_twitter', models.CharField(blank=True, max_length=250, null=True, verbose_name='Twitter Linki')),
                ('link_web', models.CharField(blank=True, max_length=250, null=True, verbose_name='Website Linki')),
            ],
            options={
                'verbose_name': 'Reklamveren',
                'verbose_name_plural': 'Reklamverenler',
            },
            bases=('djangoecommerce_app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Adres', max_length=255, verbose_name='İsim')),
                ('open_address', models.TextField(max_length=100, verbose_name='Açık Adres')),
                ('short_address', models.TextField(max_length=70, verbose_name='Kısa Adres')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Posta Kodu')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='X Koordinatı')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Y Koordinatı')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='CompanyFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='İsim')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Reklamveren Özelliği',
                'verbose_name_plural': 'Reklamveren Özellikleri',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoecommerce_app.CompanyAddress', verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoecommerce_app.City', verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='company',
            name='features',
            field=models.ManyToManyField(blank=True, to='djangoecommerce_app.CompanyFeature', verbose_name='Reklamveren Şirket Özellikleri'),
        ),
    ]
