# Generated by Django 2.0.9 on 2019-04-05 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0005_auto_20190406_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ürün Markası')),
            ],
            options={
                'verbose_name': 'Ürün Markası',
                'verbose_name_plural': 'Ürün Markaları',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('description', models.TextField(max_length=1000, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('thumbnail', models.ImageField(upload_to='images/product/', verbose_name='İsim')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='djangoecommerce_app.Brand', verbose_name='Ürün Markası')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Ürün Kategorisi')),
            ],
            options={
                'verbose_name': 'Ürün Kategorisi',
                'verbose_name_plural': 'Ürün Kategorileri',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product/', verbose_name='İsim')),
            ],
            options={
                'verbose_name': 'Ürün Resmi',
                'verbose_name_plural': 'Ürün Resimleri',
                'ordering': ('-pk',),
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Şirket', 'verbose_name_plural': 'Şirketler'},
        ),
        migrations.AlterModelOptions(
            name='companyfeature',
            options={'ordering': ('-id',), 'verbose_name': 'Şirket Özelliği', 'verbose_name_plural': 'Şirket Özellikleri'},
        ),
        migrations.AlterField(
            model_name='company',
            name='features',
            field=models.ManyToManyField(blank=True, to='djangoecommerce_app.CompanyFeature', verbose_name='Şirket Özellikleri'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoecommerce_app.Company', verbose_name='Sahibi'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sofra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoecommerce_app.Product', verbose_name='Sofra'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoecommerce_app.ProductCategory', verbose_name='Ürün Tipi'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Ürün Sahibi'),
        ),
    ]
