# Generated by Django 2.0.9 on 2019-04-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0006_auto_20190406_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
    ]
