# Generated by Django 2.0.9 on 2019-04-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoecommerce_app', '0011_activationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivationToken',
        ),
    ]
